#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01)
# write a Bash script that will display information about subdomains.

print_config ()
{
    printf "The subdomain %s is a " "$2"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    printf " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}

if [ -z "$2" ]; then
   for subs in "www" "lb-01" "web-01" "web-02"
   do
       print_config "$1" "$subs"
   done
else
    print_config "$1" "$2"
fi