#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine to:
# - Install nginx on your web-01
# - server
# - Nginx should be listening on port 80
# - When querying Nginx at its root / with a GET request (requesting a page) using curl

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod -R 755 /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start