#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod -R 755 /var/www/html
sudo echo "Hello World!" > /var/www/html/index.html
replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/linktr.ee\/ginjardev permanent;"
sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-available/default
sudo service nginx start