#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod -R 755 /var/www/html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
replacement="server_name _;\n\tlocation /redirect_me {\t\treturn 301 https://linkt.ree/ginjardev; \t}"
sudo sed -i "s#server_name _;#$replacement#" /etc/nginx/sites-enabled/default
sudo service nginx restart