#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod -R 755 /var/www/html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
replacement="server_name _;\n\tlocation /redirect_me {\t\treturn 301 https://linkt.ree/ginjardev; \t}"
sudo sed -i "s#server_name _;#$replacement#" /etc/nginx/sites-enabled/default

# create error page and add a redirect for error 404
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement404="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s#listen 80 default_server;#$replacement404#" /etc/nginx/sites-enabled/default
sudo service nginx restart
